image: maven:3.9.6-eclipse-temurin-21

pipelines:
  custom:
    run-tests:
      - variables:
          - name: SUITE_FILE
            default: ""  # Leave empty to run all tests
      - step:
          name: Run Tests
          caches:
            - maven
          script:
            - |
              if [ "$SUITE_FILE" = "" ]; then
                mvn clean test
              else
                mvn clean test -Dsurefire.suiteXmlFiles=$SUITE_FILE
              fi