image: maven:3.9.6-eclipse-temurin-21

pipelines:
  custom:
    run-tests:
      - variables:
          - name: SUITE_FILE
            default: ""  # Leave empty to run all tests
      - step:
          name: Run Tests
          caches:
            - maven
          script:
            - |
              if [ "$SUITE_FILE" = "" ]; then
                mvn clean test
              else
                mvn clean test -Dsurefire.suiteXmlFiles=$SUITE_FILE
              fi

    run-parallel-parallel:
      - variables:
          - name: PARALLEL
            default: "none"
          - name: THREAD_COUNT
            default: "5"
      - step:
          name: Run Tests with Custom Parallel Settings
          caches:
            - maven
          script:
            - mvn clean test -Dsurefire.parallel=$PARALLEL -Dsurefire.threadCount=$THREAD_COUNT

	run-flexible-tests:
	  - variables:
	      - name: SUITE_FILE
	        default: "test-suites/DummyApiTestng.xml"
	      - name: PARALLEL
	        default: "none"       # e.g., methods, classes
	      - name: THREAD_COUNT
	        default: "5"
	  - step:
	      name: Run Flexible Tests
	      caches:
	        - maven
	      script:
	        - |
	          CMD="mvn clean test -Dsurefire.parallel=$PARALLEL -Dsurefire.threadCount=$THREAD_COUNT"
	          if [ "$SUITE_FILE" != "" ]; then
	            CMD="$CMD -Dsurefire.suiteXmlFiles=$SUITE_FILE"
	          fi
	          echo "Executing: $CMD"
	          eval $CMD
